# Generated by Django 3.0.5 on 2025-03-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrecord',
            old_name='Policy',
            new_name='policy',
        ),
    ]
